---
# handlers file for vault
- name: reload systemd configuration
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart vault
  service: name=vault-server state=restarted enabled=yes
